server:
  port: ${PORT:8080}


spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none # replace after first run on "none" or "update"
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false