server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger_system
    username: postgres
    password: 12345
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # replace after first run on "none" or "update"
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false