server:
  port: 80
  servlet:
    context-path: /messenger-system

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: heroku
  application:
    name: messenger-system
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    open-in-view: true

security:
  jwt:
    iis: org.urumov
    secret: secretword
    private-key: classpath:jwt/rsa.private.key
    public-key: classpath:jwt/rsa.public.key
    token-expired-seconds:
      2592000 #1 месяц

springdoc:
  api-docs:
    enabled:
      true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui